version: '3.7'
networks:
  outside:
    external:
      name: studyalign-network
  inside:
    driver: bridge
  traefik-net:
    external: true

services:
  # builds the frontend
  study-align-framework:
    container_name: study-align-framework
    environment:
      - PUBLIC_URL=/studies
      - REACT_APP_STUDY_ALIGN_URL=PATH-TO-YOUR-STUDYALIGN-BACKEND
    build:
      context: ./
      dockerfile: Dockerfile.prod
    networks:
      - inside
    volumes:
      - ./build/:/ui/build
      - ./public:/ui/public
      - ./src/:/ui/src
  # serves the frontend
  study-align-framework-nginx:
    container_name: study-align-framework-nginx
    image: nginx
    ports:
      - 8002:80
    volumes:
      - ./build/:/ui/build
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - study-align-framework
    networks:
      - inside
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.port=8088" # port of the traefik instance
      - "traefik.docker.network=traefik-net" # traefik network
      - "traefik.http.routers.study-align-framework.rule=PathPrefix(`/studies`)" # URL path to your backend, replace YOUR-BACKEND with an unique string to name your router
      - "traefik.http.middlewares.study-align-framework.stripprefix.prefixes=/studies" # declare strip prefix middleware from above, replace strip-YOUR-PATH with an unique name
      - "traefik.http.routers.study-align-framework.middlewares=study-align-framework@docker" # add middleware that strips of your path, replace YOUR-BACKEND with the router name above, replace strip>

