export const PARTICIPATE = "PARTICIPATE";
export const ME = "ME";

export const GET_PROCEDURE = "GET_PROCEDURE";
export const START_PROCEDURE = "START_PROCEDURE";
export const NEXT_PROCEDURE = "NEXT_PROCEDURE";
export const END_PROCEDURE = "END_PROCEDURE";

export const CHECK_SURVEY_RESULT = "CHECK_SURVEY_RESULT";

export const START_NAVIGATOR = "START_NAVIGATOR";
export const RECONNECT_NAVIGATOR = "RECONNECT_NAVIGATOR";
export const CLOSE_NAVIGATOR = "CLOSE_NAVIGATOR";

